Repository Tonybsilva-dev/Peoplelitics, pull requests merged in 2022-01, with the labels that each got.

#3 Update handlingError Class
  backend/src/modules/user/useCases/createUser/services/createClientService.ts
  backend/src/shared/http/errors/AppError.ts
  backend/src/shared/http/server.ts
Labels: enhancement

#4 Find Many Users Added
  backend/package.json
  backend/src/modules/user/infra/http/routes/users.routes.ts
  backend/src/modules/user/useCases/createUser/controller/createUserController.ts
  backend/src/modules/user/useCases/createUser/services/createUserService.ts
  backend/src/modules/user/useCases/findUser/controller/findUserController.ts
  backend/src/modules/user/useCases/findUser/service/findUserService.ts
Labels: enhancement

#5 criando relacionamentos
  backend/prisma/migrations/20220110153208_create_tables/migration.sql
  backend/prisma/migrations/20220110205144_basics_relationships/migration.sql
  backend/prisma/migrations/20220110214620_alter_relation_ships/migration.sql
  backend/prisma/schema.prisma
Labels: enhancement

#6 Auth JWT added
  backend/coverage/clover.xml
  backend/coverage/coverage-final.json
  backend/coverage/lcov-report/base.css
  backend/coverage/lcov-report/block-navigation.js
  backend/coverage/lcov-report/favicon.png
  backend/coverage/lcov-report/index.html
  backend/coverage/lcov-report/modules/user/useCases/createUser/services/createUserService.ts.html
  backend/coverage/lcov-report/modules/user/useCases/createUser/services/index.html
  backend/coverage/lcov-report/prettify.css
  backend/coverage/lcov-report/prettify.js
  backend/coverage/lcov-report/shared/infra/database/index.html
  backend/coverage/lcov-report/shared/infra/database/prismaClient.ts.html
  backend/coverage/lcov-report/sort-arrow-sprite.png
  backend/coverage/lcov-report/sorter.js
  backend/coverage/lcov.info
  backend/src/@types/express/express.d.ts
  backend/src/config/auth.ts
  backend/src/modules/user/controller/index.ts
  backend/src/modules/user/infra/http/routes/users.routes.ts
  backend/src/modules/user/useCases/auth/service/AuthenticatedUserService.ts
  backend/src/modules/user/useCases/createUser/controller/createUserController.ts
  backend/src/modules/user/useCases/findUser/controller/findUserController.ts
  backend/src/shared/http/middlewares/ensureAuthenticated.ts
Labels: enhancement

#7 Bug fixed on Error Handling
  backend/.env.example
  backend/src/modules/user/useCases/auth/service/AuthenticatedUserService.ts
  backend/src/modules/user/useCases/createUser/services/createUserService.ts
  backend/src/shared/http/middlewares/globalError.ts
  backend/src/shared/http/server.ts
Labels: wontfix

#8 Feature/mongodb
  backend/package.json
  backend/src/modules/user/controller/index.ts
  backend/src/modules/user/infra/http/routes/users.routes.ts
  backend/src/modules/user/useCases/auth/service/AuthenticatedUserService.ts
  backend/src/modules/user/useCases/createUser/services/createUserService.ts
  backend/src/modules/user/useCases/findUser/service/findUserService.ts
  backend/src/shared/http/server.ts
  backend/src/shared/infra/database/mongoDB/models/Acess.ts
  backend/src/shared/infra/database/mongoDB/mongoClient.ts
  backend/src/shared/infra/database/mongoDB/utils/PointSchema.ts
  backend/src/shared/infra/database/prisma/prismaClient.ts
  backend/yarn.lock
Labels: enhancement

#9 Password improve security added
  backend/src/modules/user/functions/checkPasswordSecurity.ts
  backend/src/modules/user/useCases/createUser/services/createUserService.ts
Labels: enhancement

#11 Fixed structure and router to ACL
  backend/src/modules/acessControlList/controller/index.ts
  backend/src/modules/acessControlList/infra/http/routes/acl.routes.ts
  backend/src/modules/acessControlList/useCases/createPermissions.ts/createPermissionService.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRoleService.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRolesPermissionsService.ts
  backend/src/modules/acessControlList/useCases/createUserAccessControlList/createUserACLService.ts
  backend/src/modules/auth/controller/index.ts
  backend/src/modules/auth/infra/http/routes/auth.routes.ts
  backend/src/modules/auth/service/AuthenticatedUserService.ts
  backend/src/modules/user/controller/index.ts
  backend/src/modules/user/infra/http/routes/users.routes.ts
  backend/src/shared/http/routes/index.ts
Labels: enhancement, wontfix

#13 scripts Eraser added
  backend/package.json
  backend/src/modules/auth/service/AuthenticatedUserService.ts
  backend/src/shared/http/routes/index.ts
  backend/src/shared/http/server.ts
  backend/src/shared/infra/database/mongoDB/models/Access.ts
  backend/src/shared/scripts/EraserHead.ts
  backend/yarn.lock
Labels: enhancement

#32 Feature/ddd structure
  backend/src/modules/acessControlList/controller/index.ts
  backend/src/modules/acessControlList/infra/http/routes/acl.routes.ts
  backend/src/modules/acessControlList/routes/acl.routes.ts
  backend/src/modules/acessControlList/useCases/createPermissions.ts/createPermissionService.ts
  backend/src/modules/acessControlList/useCases/createPermissions.ts/createPermissionsController.ts
  backend/src/modules/acessControlList/useCases/createPermissions.ts/createPermissionsDTO.ts
  backend/src/modules/acessControlList/useCases/createPermissions.ts/index.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRoleController.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRoleDTO.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRolePermissionsController.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRolePermissionsDTO.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRoleService.ts
  backend/src/modules/acessControlList/useCases/createRoles/createRolesPermissionsService.ts
  backend/src/modules/acessControlList/useCases/createRoles/index.ts
  backend/src/modules/acessControlList/useCases/createUserAccessControlList/createUserACLController.ts
  backend/src/modules/acessControlList/useCases/createUserAccessControlList/createUserACLDTO.ts
  backend/src/modules/acessControlList/useCases/createUserAccessControlList/createUserACLService.ts
  backend/src/modules/acessControlList/useCases/createUserAccessControlList/index.ts
  backend/src/modules/auth/controller/index.ts
  backend/src/modules/auth/infra/http/routes/auth.routes.ts
  backend/src/modules/auth/routes/auth.routes.ts
  backend/src/modules/auth/useCase/AuthUserController.ts
  backend/src/modules/auth/useCase/AuthUserDTO.ts
  backend/src/modules/auth/useCase/AuthUserService.ts
  backend/src/modules/auth/useCase/index.ts
  backend/src/modules/user/controller/index.ts
  backend/src/modules/user/infra/http/routes/users.routes.ts
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/createUser/createUserController.ts
  backend/src/modules/user/useCases/createUser/createUserDTO.ts
  backend/src/modules/user/useCases/createUser/createUserService.ts
  backend/src/modules/user/useCases/createUser/index.ts
  backend/src/modules/user/useCases/findUser/findUserController.ts
  backend/src/modules/user/useCases/findUser/findUserDTO.ts
  backend/src/modules/user/useCases/findUser/findUserService.ts
  backend/src/modules/user/useCases/findUser/index.ts
  backend/src/modules/utils/checkPasswordSecurity.ts
  backend/src/shared/http/app.ts
  backend/src/shared/http/routes/index.ts
  backend/src/shared/http/server.ts
  backend/src/shared/infra/database/mongoDB/scripts/EraserHead.ts
Labels: enhancement

#33 Feature/users crud
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserController.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserDTO.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserService.ts
  backend/src/modules/user/useCases/deleteUser/index.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserController.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserDTO.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserService.ts
  backend/src/modules/user/useCases/findManyUser/index.ts
  backend/src/modules/user/useCases/findUser/findUserController.ts
  backend/src/modules/user/useCases/findUser/findUserDTO.ts
  backend/src/modules/user/useCases/findUser/findUserService.ts
  backend/src/modules/user/useCases/findUser/index.ts
  backend/src/modules/utils/checkValidEmail.ts
Labels: enhancement

#35 ajustando o schema do user
  backend/prisma/migrations/20220117222737_att_user_schema/migration.sql
  backend/prisma/schema.prisma
Labels: enhancement

#34 added updateUser and CamelCase
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/createUser/createUserController.ts
  backend/src/modules/user/useCases/createUser/createUserService.ts
  backend/src/modules/user/useCases/createUser/index.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserController.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserDTO.ts
  backend/src/modules/user/useCases/deleteUser/deleteUserService.ts
  backend/src/modules/user/useCases/deleteUser/index.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserController.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserDTO.ts
  backend/src/modules/user/useCases/findManyUser/findManyUserService.ts
  backend/src/modules/user/useCases/findManyUser/index.ts
  backend/src/modules/user/useCases/findUser/findUserController.ts
  backend/src/modules/user/useCases/findUser/findUserDTO.ts
  backend/src/modules/user/useCases/findUser/findUserService.ts
  backend/src/modules/user/useCases/findUser/index.ts
  backend/src/modules/user/useCases/updateUser/index.ts
  backend/src/modules/user/useCases/updateUser/updateUserController.ts
  backend/src/modules/user/useCases/updateUser/updateUserDTO.ts
  backend/src/modules/user/useCases/updateUser/updateUserService.ts
Labels: enhancement

#40 Hml/ti
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/findUser/findUserController.ts
  backend/src/modules/user/useCases/updateUser/updateUserController.ts
  backend/src/modules/user/useCases/updateUser/updateUserDTO.ts
  backend/src/modules/user/useCases/updateUser/updateUserService.ts
Labels: enhancement

#41 uploadAvatarUser
  backend/.gitignore
  backend/package.json
  backend/src/config/uploads.ts
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/updateUser/updateUserService.ts
  backend/src/modules/user/useCases/uploadAvatarUser/index.ts
  backend/src/modules/user/useCases/uploadAvatarUser/uploadAvatarUserController.ts
  backend/src/modules/user/useCases/uploadAvatarUser/uploadAvatarUserDTO.ts
  backend/src/modules/user/useCases/uploadAvatarUser/uploadAvatarUserService.ts
  backend/yarn.lock
Labels: enhancement

#42 updateUserPassword
  backend/src/modules/user/routes/users.routes.ts
  backend/src/modules/user/useCases/updateUserPassword/index.ts
  backend/src/modules/user/useCases/updateUserPassword/updateUserPasswordController.ts
  backend/src/modules/user/useCases/updateUserPassword/updateUserPasswordDTO.ts
  backend/src/modules/user/useCases/updateUserPassword/updateUserPasswordUserService.ts
Labels: enhancement
